language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a
    
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    
    
    # The BuildTools version used by the project
    - build-tools-25.0.1

    # The SDK version used to compile the project
    - android-25

    # Repositories for Gradle and Maven
    - extra-android-m2repository
    - extra-google-m2repository
    - tools
    - extra
    - extra-google-google_play_services
    - build-tools-25.0.1
    - extra-android-m2repository
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew
 
notifications:

slack: siot-miage:2a022WNT3zbXYEpvyfGsEXmN
 
script:
  - ./gradlew clean build